version: 2

models:
  - name: fct_merchant_performance
    description: |
      Merchant cohort retention analysis tracking activity, revenue, and health status.
      
      **Data Period:** Jan 2017 - Aug 2018 (clean data period identified in EDA)
      
      **Key Metrics:**
      - 6-month retention: ~59% (41% churn rate)
      - 3-month retention: ~73% (27% churn rate)
      
      **Use Cases:**
      - Cohort retention analysis
      - Merchant churn prediction
      - Revenue forecasting
      - Health monitoring dashboards
    
    columns:
      - name: seller_id
        description: Unique merchant identifier
        tests:
          - not_null
          - unique
      
      - name: cohort_month
        description: Month merchant first joined platform (for cohort analysis)
        tests:
          - not_null
      
      - name: first_sale_at
        description: Timestamp of merchant's first sale on platform
      
      - name: active_months
        description: Number of distinct months merchant had at least one order
      
      - name: total_orders
        description: Lifetime orders fulfilled by merchant
      
      - name: total_revenue
        description: Lifetime revenue generated by merchant (in local currency)
      
      - name: retained_3_months
        description: Binary flag - 1 if merchant active 3+ months after joining
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]
      
      - name: retained_6_months
        description: |
          Binary flag - 1 if merchant active 6+ months after joining.
          Used to calculate ~41% 6-month churn rate.
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]
      
      - name: merchant_health_status
        description: |
          Current merchant status based on recency:
          - Active: Sold within last month
          - At Risk: No sales for 2-3 months
          - Churned: No sales for 3+ months
        tests:
          - not_null
          - accepted_values:
              arguments: 
                values: ['Active', 'At Risk', 'Churned']
      
      - name: avg_monthly_revenue
        description: Average revenue per active month (total_revenue / active_months)
      
      - name: avg_monthly_orders
        description: Average orders per active month (total_orders / active_months)
  - name: fct_customer_cohorts
    description: |
      Customer cohort analysis tracking first-order delivery experience and lifetime behavior.
      
      **Data Period:** Jan 2017 - May 2018 cohorts (customers with 3+ months to show repeat behavior)
      
      **Key Findings:**
      - Overall repeat purchase rate: 3.6%
      - On-time first delivery: 3.64% repeat rate
      - Delayed first delivery (>3 days): 2.80% repeat rate
      - **23% reduction in repeat purchases from delivery delays**
      
      **Business Impact:** 
      Even though 95% of deliveries are on-time, the 5% with delays show significantly 
      worse customer retention. First-order experience is critical for building repeat customers.
      
      **Use Cases:**
      - Customer lifetime value analysis
      - Delivery performance impact studies
      - Cohort retention tracking
      - Marketing segmentation (repeat vs one-time buyers)
    
    columns:
      - name: customer_unique_id
        description: Unique customer identifier (consistent across multiple orders)
        tests:
          - not_null
          - unique
      
      - name: first_order_at
        description: Timestamp of customer's first order on platform
        tests:
          - not_null
      
      - name: cohort_month
        description: Month customer first ordered (for cohort analysis)
        tests:
          - not_null
      
      - name: first_order_id
        description: Order ID of customer's first purchase
        tests:
          - not_null
      
      - name: first_order_delivered_on_time
        description: |
          Binary flag for first order delivery performance:
          - 1 = Delivered within 3 days of estimate (on-time)
          - 0 = Delivered >3 days after estimate (delayed)
          
          Used to calculate 23% reduction in repeat purchases from delays.
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['0', '1']
      
      - name: first_order_delivery_delay_days
        description: |
          Days between estimated and actual delivery on first order.
          Negative values = early delivery (merchant over-estimated)
          Positive values = late delivery
      
      - name: customer_state
        description: Brazilian state where customer is located (2-letter code)
        tests:
          - not_null
      
      - name: customer_city
        description: City where customer is located
      
      - name: active_months
        description: Number of distinct months customer placed at least one order
        tests:
          - not_null
      
      - name: total_revenue
        description: Lifetime revenue from customer (sum of all order payments)
      
      - name: total_orders
        description: Total number of orders placed by customer
        tests:
          - not_null
      
      - name: is_repeat_customer
        description: |
          Binary flag indicating repeat purchase behavior:
          - 1 = Customer placed 2+ orders (repeat customer)
          - 0 = Customer placed only 1 order (one-time buyer)
          
          Overall repeat rate: ~3.6%
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['0', '1']
      
      - name: avg_order_value
        description: Average order value (total_revenue / total_orders)
      
      - name: months_since_first_order
        description: |
          Months between first order and dataset end (Aug 2018).
          Used to identify how long customers have been in the cohort.
  - name: fct_delivery_impact
    description: |
      Order-level delivery performance analysis tracking merchant fulfillment quality and customer experience.
      
      **Data Period:** Jan 2017 - Aug 2018 (delivered orders only)
      
      **Key Metrics:**
      - 95% of deliveries within acceptable range (≤3 days delay)
      - 5% experience significant delays (>3 days)
      - Average delivery delay: varies by merchant and geography
      
      **Use Cases:**
      - Identify problematic merchants with chronic delays
      - Analyze geographic delivery performance patterns
      - Track same-state vs cross-state fulfillment efficiency
      - Correlate delivery performance with customer retention
    
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - not_null
          - unique
      
      - name: customer_unique_id
        description: Unique customer identifier (consistent across orders)
        tests:
          - not_null
      
      - name: seller_id
        description: Merchant who fulfilled this order
        tests:
          - not_null
      
      - name: ordered_at
        description: Timestamp when order was placed
        tests:
          - not_null
      
      - name: delivered_to_customer_at
        description: Actual delivery timestamp
        tests:
          - not_null
      
      - name: estimated_delivery_at
        description: Promised delivery date provided at order time
        tests:
          - not_null
      
      - name: delivery_delay_days
        description: |
          Days between actual and estimated delivery.
          Negative = early delivery, Positive = late delivery
      
      - name: delivery_on_time
        description: |
          Binary flag for acceptable delivery performance:
          - '1' = Delivered within 3 days of estimate (on-time)
          - '0' = Delivered >3 days after estimate (delayed)
        tests:
          - not_null
          - accepted_values:
              arguments: 
                values: ['0', '1']
      
      - name: delivery_status
        description: |
          Categorical delivery performance:
          - 'Early': Delivered >7 days early
          - 'On-Time': Within acceptable range (-7 to +3 days)
          - 'Slightly Late': Minor delay (3-10 days)
          - 'Very Late': Major delay (>10 days)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Early', 'On Time', 'Slightly Late', 'Very Late']
      
      - name: customer_state
        description: Brazilian state where customer is located
        tests:
          - not_null
      
      - name: customer_city
        description: City where customer is located
      
      - name: seller_state
        description: Brazilian state where merchant is located
        tests:
          - not_null
      
      - name: seller_city
        description: City where merchant is located
      
      - name: same_state
        description: |
          Binary flag indicating if customer and seller in same state:
          - '1' = Same state (local fulfillment)
          - '0' = Different states (cross-state shipping)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['0', '1']
      
      - name: order_value
        description: Total payment amount for this order
      
      - name: num_items
        description: Number of items in this order
        tests:
          - not_null
      
      - name: product_category
        description: |
          Product category (English) for single-item orders.
          NULL for multi-item orders with mixed categories.
      
      - name: order_year
        description: Year order was placed (for time-series analysis)
      
      - name: order_month
        description: Month order was placed (for seasonality analysis)
      
      - name: order_quarter
        description: Quarter order was placed (for quarterly reporting)
      
      - name: day_of_week
        description: Day of week order was placed (1=Sunday, 7=Saturday)