version: 2

models:
  - name: fct_merchant_performance
    description: |
      Merchant cohort retention analysis tracking activity, revenue, and health status.
      
      **Data Period:** Jan 2017 - Aug 2018 (clean data period identified in EDA)
      
      **Key Metrics:**
      - 6-month retention: ~59% (41% churn rate)
      - 3-month retention: ~73% (27% churn rate)
      
      **Use Cases:**
      - Cohort retention analysis
      - Merchant churn prediction
      - Revenue forecasting
      - Health monitoring dashboards
    
    columns:
      - name: seller_id
        description: Unique merchant identifier
        tests:
          - not_null
          - unique
      
      - name: cohort_month
        description: Month merchant first joined platform (for cohort analysis)
        tests:
          - not_null
      
      - name: first_sale_at
        description: Timestamp of merchant's first sale on platform
      
      - name: active_months
        description: Number of distinct months merchant had at least one order
      
      - name: total_orders
        description: Lifetime orders fulfilled by merchant
      
      - name: total_revenue
        description: Lifetime revenue generated by merchant (in local currency)
      
      - name: retained_3_months
        description: Binary flag - 1 if merchant active 3+ months after joining
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]
      
      - name: retained_6_months
        description: |
          Binary flag - 1 if merchant active 6+ months after joining.
          Used to calculate ~41% 6-month churn rate.
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]
      
      - name: merchant_health_status
        description: |
          Current merchant status based on recency:
          - Active: Sold within last month
          - At Risk: No sales for 2-3 months
          - Churned: No sales for 3+ months
        tests:
          - not_null
          - accepted_values:
              arguments: 
                values: ['Active', 'At Risk', 'Churned']
      
      - name: avg_monthly_revenue
        description: Average revenue per active month (total_revenue / active_months)
      
      - name: avg_monthly_orders
        description: Average orders per active month (total_orders / active_months)